spring:
  datasource:
    url: jdbc:mysql://localhost:3333/instagram?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
